# LOGIC HEADER
# Input:          Synthetic receipt PNGs generated by the make_receipt_image fixture.
# Transformation: Run process_batch() end-to-end through the vendored rule_based engine
#                 and verify the run summary and flagged-item persistence are correct.
# Output:         Pass/fail assertions.

from pathlib import Path

from api.processor import process_batch
from api.storage import Storage


def _open_files(paths):
    return [(p.name, open(p, "rb")) for p in paths]


def test_process_batch_clean_receipts(isolated_cwd, make_receipt_image):
    storage = Storage(db_path=isolated_cwd / "test.db")
    img_dir = isolated_cwd / "in"
    img_dir.mkdir()
    p1 = make_receipt_image(img_dir / "r1.png", "Corner Cafe", "2026-01-05", "12.50")
    p2 = make_receipt_image(img_dir / "r2.png", "TechMart", "2026-01-06", "45.00")

    files = _open_files([p1, p2])
    try:
        summary = process_batch(files, storage, engine="rule_based")
    finally:
        for _, f in files:
            f.close()

    assert summary["files_processed"] == 2
    assert summary["run_id"] is not None
    runs = storage.list_runs()
    assert len(runs) == 1
    assert runs[0].files_processed == 2


def test_process_batch_flags_duplicates(isolated_cwd, make_receipt_image):
    storage = Storage(db_path=isolated_cwd / "test.db")
    img_dir = isolated_cwd / "in"
    img_dir.mkdir()
    p1 = make_receipt_image(img_dir / "r1.png", "Corner Cafe", "2026-01-05", "12.50")
    p2 = img_dir / "r1_copy.png"
    p2.write_bytes(p1.read_bytes())  # exact byte-for-byte duplicate

    files = _open_files([p1, p2])
    try:
        summary = process_batch(files, storage, engine="rule_based")
    finally:
        for _, f in files:
            f.close()

    assert summary["duplicate_count"] == 1
    assert summary["flagged_count"] >= 1
    flagged = storage.list_flagged_items()
    assert any("duplicate_of" in item.reason for item in flagged)


def test_process_batch_flags_unreadable_file(isolated_cwd):
    storage = Storage(db_path=isolated_cwd / "test.db")
    img_dir = isolated_cwd / "in"
    img_dir.mkdir()
    bad = img_dir / "not_really_an_image.png"
    bad.write_bytes(b"this is not valid image data at all")

    files = _open_files([bad])
    try:
        summary = process_batch(files, storage, engine="rule_based")
    finally:
        for _, f in files:
            f.close()

    assert summary["files_processed"] == 1
    assert summary["flagged_count"] == 1
    flagged = storage.list_flagged_items()
    assert flagged[0].reason.startswith("no_data_extracted") or flagged[0].reason.startswith("extraction_failed")
